# ARG BASE_IMAGE=nvidia/cudagl:10.0-devel-ubuntu16.04
# FROM $BASE_IMAGE

# RUN apt-get update
# RUN apt-get install \
# 	python3 \
# 	python3-pip \
# 	sudo \
# 	libglu1-mesa-dev \
# 	xdg-user-dirs \
# 	pulseaudio \
# 	sudo \
# 	x11-xserver-utils \
#     git \
#     build-essential \
#     wget \
#     rsync \
# 	-y --no-install-recommends
# RUN pip3 install setuptools wheel
# #RUN pip3 install airsim

# RUN adduser --force-badname --disabled-password --gecos '' --shell /bin/bash airsim_user && \ 
# 	echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \ 
# 	adduser airsim_user sudo && \ 
# 	adduser airsim_user audio && \ 
# 	adduser airsim_user video

# USER airsim_user
# WORKDIR /home/airsim_user
# RUN mkdir -p /home/airsim_user/Documents/
# WORKDIR /home/airsim_user/Documents/
# RUN echo 'Cloning AirSim from Heron Systems'
# RUN git clone --progress https://github.com/heronsystems/AirSim.git
# WORKDIR /home/airsim_user/Documents/AirSim/
# RUN ./setup.sh
# RUN ./build.sh
# RUN sudo apt-get install -y python3-setuptools
# RUN pip3 install setuptools wheel
# WORKDIR /home/airsim_user/Documents/AirSim/PythonClient
# RUN sudo python3 setup.py develop
# WORKDIR /home/airsim_user/Documents/AirSim/
# COPY settings.json /home/airsim_user/Documents/AirSim
# #ADD Documents /home/airsim_user/Documents

# RUN sudo chown -R airsim_user /home/airsim_user


# OLD CODE BELOW:
ARG BASE_IMAGE=adamrehn/ue4-engine:4.19.2-cudagl10.0
FROM $BASE_IMAGE

USER root
RUN apt-get update
RUN apt-get install \
	rsync \
   sudo \
   wget \
   x11-xserver-utils \
   -y --no-install-recommends

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \ 
   adduser ue4 sudo 

USER ue4
RUN cd /home/ue4 && \
	git clone --progress https://github.com/heronsystems/AirSim.git && \
	cd AirSim && \
	./setup.sh && \
	./build.sh

#WORKDIR /home/ue4/AirSim/PythonClient
#RUN pip3 install setuptools wheel
#RUN sudo python3 setup.py develop
	
WORKDIR /home/ue4